#> manual page: `man alacritty-bindings` - alacritty 0.17.0
#[I] remove all keybindings 
#? so I can redefine them and not get surprised on some key strokes


# MOUSE BINDINGS
[mouse]
bindings = [
    { mouse = "Right", action = "None"},
    { mouse = "Right", mods = "Control", action = "None"},
    { mouse = "Middle", mode = "~Vi", action = "None"}
]


[keyboard]
bindings = [
    # KEY BINDINGS
    { key = "Paste", action = "None" },
    { key = "Copy", action = "None" },
    { key = "L", mods = "Control", action = "None" },
    { key = "Paste", mode = "Vi|Search", action = "None" },
    { key = "L", mods = "Control", mode = "~Vi|~Search", action = "None" },
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "None" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "None" },
    { key = "Home", mods = "Shift", mode = "~Alt", action = "None" },
    { key = "End", mods = "Shift", mode = "~Alt", action = "None" },
    # Vi Mode
    { key = "Space", mods = "Shift|Control", mode = "~Search", action = "None" },
    { key = "Space", mods = "Shift|Control", mode = "Vi|~Search", action = "None" },
    { key = "Escape", mode = "Vi|~Search", action = "None" },
    { key = "I", mode = "Vi|~Search", action = "None" },
    { key = "I", mode = "Vi|~Search", action = "None" },
    { key = "C", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "Y", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "E", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "G", mode = "Vi|~Search", action = "None" },
    { key = "G", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "B", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "F", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "U", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "D", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "Y", mode = "Vi|~Search", action = "None" },
    { key = "Y", mode = "Vi|~Search", action = "None" },
    { key = "Copy", mode = "Vi|~Search", action = "None" },
    { key = "Y", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "Y", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "Y", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "Y", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "V", mode = "Vi|~Search", action = "None" },
    { key = "V", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "V", mods = "Control", mode = "Vi|~Search", action = "None" },
    { key = "V", mods = "Alt", mode = "Vi|~Search", action = "None" },
    { key = "Enter", mode = "Vi|~Search", action = "None" },
    { key = "Z", mode = "Vi|~Search", action = "None" },
    { key = "F", mode = "Vi|~Search", action = "None" },
    { key = "F", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "T", mode = "Vi|~Search", action = "None" },
    { key = "T", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = ";", mode = "Vi|~Search", action = "None" },
    { key = ",", mode = "Vi|~Search", action = "None" },
    { key = "*", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "#", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "K", mode = "Vi|~Search", action = "None" },
    { key = "J", mode = "Vi|~Search", action = "None" },
    { key = "H", mode = "Vi|~Search", action = "None" },
    { key = "L", mode = "Vi|~Search", action = "None" },
    { key = "ArrowUp", mode = "Vi|~Search", action = "None" },
    { key = "ArrowDown", mode = "Vi|~Search", action = "None" },
    { key = "ArrowLeft", mode = "Vi|~Search", action = "None" },
    { key = "ArrowRight", mode = "Vi|~Search", action = "None" },
    { key = "0", mode = "Vi|~Search", action = "None" },
    { key = "$", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "Home", mode = "Vi|~Search", action = "None" },
    { key = "End", mode = "Vi|~Search", action = "None" },
    { key = "^", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "H", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "M", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "L", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "B", mode = "Vi|~Search", action = "None" },
    { key = "W", mode = "Vi|~Search", action = "None" },
    { key = "E", mode = "Vi|~Search", action = "None" },
    { key = "B", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "W", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "E", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "%", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "{", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "}", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "/", mode = "Vi|~Search", action = "None" },
    { key = "?", mods = "Shift", mode = "Vi|~Search", action = "None" },
    { key = "N", mode = "Vi|~Search", action = "None" },
    { key = "N", mods = "Shift", mode = "Vi|~Search", action = "None" },
    # Search Mode
    { key = "Enter", mode = "Search|Vi", action = "None" },
    { key = "Escape", mode = "Search", action = "None" },
    { key = "C", mods = "Control", mode = "Search", action = "None" },
    { key = "U", mods = "Control", mode = "Search", action = "None" },
    { key = "W", mods = "Control", mode = "Search", action = "None" },
    { key = "P", mods = "Control", mode = "Search", action = "None" },
    { key = "N", mods = "Control", mode = "Search", action = "None" },
    { key = "ArrowUp", mode = "Search", action = "None" },
    { key = "ArrowDown", mode = "Search", action = "None" },
    { key = "Enter", mode = "Search|~Vi", action = "None" },
    # Windows, Linux, and BSD only
    { key = "V", mods = "Control|Shift", mode = "~Vi", action = "None" },
    { key = "V", mods = "Control|Shift", mode = "Vi|Search", action = "None" },
    { key = "C", mods = "Control|Shift", action = "None" },
    { key = "F", mods = "Control|Shift", mode = "~Search", action = "None" },
    { key = "B", mods = "Control|Shift", mode = "~Search", action = "None" },
    { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "None" },
    { key = "Insert", mods = "Shift", action = "None" },
    { key = "0", mods = "Control", action = "None" },
    { key = "=", mods = "Control", action = "None" },
    { key = "+", mods = "Control", action = "None" },
    { key = "NumpadAdd", mods = "Control", action = "None" },
    { key = "-", mods = "Control", action = "None" },
    { key = "NumpadSubtract", mods = "Control", action = "None" },
    # Windows Only
    { key = "Enter", mods = "Alt", action = "None" },
    # MacOS Only
    { key = "K", mods = "Command", mode = "~Vi|~Search", action = "None" },
    { key = "K", mods = "Command", mode = "~Vi|~Search", action = "None" },
    { key = "0", mods = "Command", action = "None" },
    { key = "=", mods = "Command", action = "None" },
    { key = "+", mods = "Command", action = "None" },
    { key = "NumpadAdd", mods = "Command", action = "None" },
    { key = "-", mods = "Command", action = "None" },
    { key = "NumpadSubtract", mods = "Command", action = "None" },
    { key = "V", mods = "Command", mode = "~Vi", action = "None" },
    { key = "V", mods = "Command", mode = "Vi|Search", action = "None" },
    { key = "C", mods = "Command", action = "None" },
    { key = "C", mods = "Command", mode = "Vi|~Search", action = "None" },
    { key = "H", mods = "Command", action = "None" },
    { key = "H", mods = "Command|Alt", action = "None" },
    { key = "M", mods = "Command", action = "None" },
    { key = "Q", mods = "Command", action = "None" },
    { key = "W", mods = "Command", action = "None" },
    { key = "N", mods = "Command", action = "None" },
    { key = "T", mods = "Command", action = "None" },
    { key = "F", mods = "Command|Control", action = "None" },
    { key = "F", mods = "Command", mode = "~Search", action = "None" },
    { key = "B", mods = "Command", mode = "~Search", action = "None" },
    { key = "]", mods = "Command|Shift", action = "None" },
    { key = "[", mods = "Command|Shift", action = "None" },
    { key = "Tab", mods = "Command", action = "None" },
    { key = "Tab", mods = "Command|Shift", action = "None" },
    { key = "1", mods = "Command", action = "None" },
    { key = "2", mods = "Command", action = "None" },
    { key = "3", mods = "Command", action = "None" },
    { key = "4", mods = "Command", action = "None" },
    { key = "5", mods = "Command", action = "None" },
    { key = "6", mods = "Command", action = "None" },
    { key = "7", mods = "Command", action = "None" },
    { key = "8", mods = "Command", action = "None" },
    { key = "9", mods = "Command", action = "None" }
]

