#> https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/seoul256-light.toml",
    "~/.config/alacritty/keybindings/reset-defaults.toml",
    "~/.config/alacritty/keybindings/keybindings.toml"
]

[env]
SHELL="/bin/zsh"
# TODO: templatize hardcoded HOME directory
ZDOTDIR="/Users/konradodwrot/.config/zsh"

[window]
padding = { x = 3, y = 3 }
dimensions = { columns = 104, lines = 120 }
decorations = "Buttonless"
opacity = 0.8
blur = true
title = "terminal"
level = "Normal"
option_as_alt = "Both"


[scrolling]
history = 100000
multiplier = 2

[font]
normal = {family = "SauceCodePro Nerd Font Mono", style = "Regular"}
size = 18

[selection]
semantic_escape_chars = ""
save_to_clipboard = false

[cursor]
style = { shape = "Beam", blinking = "Off"}
unfocused_hollow = false
thickness = 0.5

[terminal]

shell = { program = "/bin/zsh", args = ["--login", "--no-globalrcs"]}

[hints]
enabled = []
